### PR TITLE
Application logo

### PR DESCRIPTION
**Pull request by vanshsoni**
Reference #1

### CODE REVIEW

**Comment by opticod** [comment]
@vanshsoni, Can you replace the default app icon with this one and share the screenshot of the app icon from android home screen.

**Comment by vanshsoni** [comment]
cb4ce77a-bbd5-4b3e-b1f9-c74802d7c748
Please Check It

**Comment by Logan1x** [comment]
@vanshsoni  Quality of the image is low everything else is looking fine.

**Comment by vanshsoni** [comment]
@Logan1x I take screenshot just reference for @opticod not for submitting screen image 
My task is only to design logo and I have tried to fix into app

**Comment by opticod** [comment]
Is it a big deal to increase the pixel size of the current image file? If you just create the same image in similar way like the current one but with bigger pixel size, then it will looks good in the app too. :smile:

**Comment by vanshsoni** [comment]
I have one more logo for this
icon
Sorry I am not able to do that image in high-resolution mode.

**Comment by opticod** [comment]
Just of curiosity, Can you assure us that this is your own work and not copied from any where else ?

**Comment by vanshsoni** [comment]
@opticod, the First logo is created using online tool but the second one is created using photoshop if u need I can share PSD file with you

I am not copying anything if u think u can reject PR 
Thanks

**Review by opticod — APPROVED** [review]
@vanshsoni Good Work! Merging!

**Pull request merged**
